services:
  database:
    build:
      context: ./Database
    ports:
      [5430:5432]

    volumes:
      [./db-data/:/var/lib/postgresql/data/]
  
  api: 
    build:
      context: ./Backend
    depends_on:
      - database  
    ports:
      [5000:5000]
    env_file:
      - .env